// AUTO-GENERATED by scripts/generate-family-factors.ts — do not edit by hand.
import type { FamilyFactorTable } from "./types";

export const FAMILY_FACTOR_TABLE: FamilyFactorTable = {
  porscheWide: { factor: 0.9, soldN: 0, askingN: 0 },
  byFamily: {},
  generatedAt: "1970-01-01T00:00:00Z",
};
