"use client"

import type { InvestmentNarrative } from "@/lib/fairValue/types"

interface InvestmentStoryBlockProps {
  narrative: InvestmentNarrative | null | undefined
}

export function InvestmentStoryBlock({ narrative }: InvestmentStoryBlockProps) {
  if (!narrative?.story) return null

  return (
    <section className="rounded-xl border border-border bg-card p-5 space-y-3">
      <h3 className="font-serif text-[15px] font-semibold">{/* [HARDCODED] */}Investment Story</h3>

      <div className="prose prose-sm dark:prose-invert max-w-none text-[13px] leading-relaxed">
        {narrative.story.split("\n\n").map((paragraph, i) => (
          <p key={i}>{paragraph}</p>
        ))}
      </div>

      <p className="text-[11px] text-muted-foreground">
        {/* [HARDCODED] */}Generated by {narrative.generatedBy} · {new Date(narrative.generatedAt).toLocaleDateString()}
      </p>
    </section>
  )
}
