import { readFileSync, writeFileSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";
import { getExchangeRates } from "@/lib/exchangeRates";
import { derivePrice } from "@/lib/pricing/derivePrice";
import { computeFactorTable } from "../src/lib/pricing/computeFactorTable";
import type { DerivedPrice, FamilyFactorTable } from "@/lib/pricing/types";

// Re-export for tests
export { computeFactorTable };

async function main() {
  const env = Object.fromEntries(
    readFileSync(".env.local", "utf8")
      .split("\n")
      .filter((l) => l && !l.startsWith("#") && l.includes("="))
      .map((l) => [l.slice(0, l.indexOf("=")).trim(), l.slice(l.indexOf("=") + 1).trim()]),
  );
  const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL ?? env.SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY, {
    auth: { persistSession: false },
  });
  const rates = await getExchangeRates();

  const prices: DerivedPrice[] = [];
  const pageSize = 1000;
  let from = 0;
  const SAFETY_CAP = 100_000;
  while (true) {
    let data: any[] | null = null;
    try {
      const res = await sb
        .from("listings")
        .select("source,status,year,make,model,hammer_price,final_price,current_bid,original_currency")
        .eq("make", "Porsche")
        .range(from, from + pageSize - 1);
      if (res.error) throw res.error;
      data = res.data;
    } catch (e) {
      throw new Error(`supabase paginated fetch failed at from=${from}, pageSize=${pageSize}: ${(e as Error).message}`);
    }
    if (!data || data.length === 0) break;
    for (const row of data) prices.push(derivePrice(row as any, { rates }));
    console.log(`paginated: ${prices.length} rows processed so far`);
    if (prices.length >= SAFETY_CAP) {
      console.warn(`SAFETY STOP: processed ${prices.length} rows (cap=${SAFETY_CAP}); aborting pagination`);
      break;
    }
    from += pageSize;
  }

  const table = computeFactorTable(prices);
  const body = `// AUTO-GENERATED by scripts/generate-family-factors.ts — do not edit by hand.
import type { FamilyFactorTable } from "./types";

export const FAMILY_FACTOR_TABLE: FamilyFactorTable = ${JSON.stringify(table, null, 2)};
`;
  writeFileSync("src/lib/pricing/familyFactor.generated.ts", body);
  console.log("Wrote factor table:", table.porscheWide, "families:", Object.keys(table.byFamily));
}

// Allow both `node` CJS check and ESM. Support tsx execution.
const invokedDirectly =
  typeof require !== "undefined" && typeof module !== "undefined" && require.main === module;
if (invokedDirectly || process.argv[1]?.endsWith("generate-family-factors.ts")) {
  main().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
