import { readFileSync, writeFileSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";
import { getExchangeRates } from "@/lib/exchangeRates";
import { derivePrice } from "@/lib/pricing/derivePrice";
import type { DerivedPrice, FamilyFactorTable } from "@/lib/pricing/types";

const MIN_FAMILY_SOLD = 30;

function median(values: number[]): number {
  if (values.length === 0) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
}

export function computeFactorTable(prices: DerivedPrice[]): FamilyFactorTable {
  const allSold: number[] = [];
  const allAsking: number[] = [];
  const byFamilySold = new Map<string, number[]>();
  const byFamilyAsking = new Map<string, number[]>();

  for (const p of prices) {
    if (p.basis === "sold" && p.soldPriceUsd != null) {
      allSold.push(p.soldPriceUsd);
      if (p.family) {
        if (!byFamilySold.has(p.family)) byFamilySold.set(p.family, []);
        byFamilySold.get(p.family)!.push(p.soldPriceUsd);
      }
    } else if (p.basis === "asking" && p.askingPriceUsd != null) {
      allAsking.push(p.askingPriceUsd);
      if (p.family) {
        if (!byFamilyAsking.has(p.family)) byFamilyAsking.set(p.family, []);
        byFamilyAsking.get(p.family)!.push(p.askingPriceUsd);
      }
    }
  }

  const askMedianGlobal = median(allAsking);
  const soldMedianGlobal = median(allSold);
  const porscheWide = {
    factor: askMedianGlobal > 0 && soldMedianGlobal > 0 ? soldMedianGlobal / askMedianGlobal : 0,
    soldN: allSold.length,
    askingN: allAsking.length,
  };

  const byFamily: FamilyFactorTable["byFamily"] = {};
  for (const [family, solds] of byFamilySold.entries()) {
    if (solds.length < MIN_FAMILY_SOLD) continue;
    const asks = byFamilyAsking.get(family) ?? [];
    const askMed = median(asks);
    const soldMed = median(solds);
    if (askMed > 0 && soldMed > 0) {
      byFamily[family] = { family, factor: soldMed / askMed, soldN: solds.length, askingN: asks.length };
    }
  }

  return { porscheWide, byFamily, generatedAt: new Date().toISOString() };
}

async function main() {
  const env = Object.fromEntries(
    readFileSync(".env.local", "utf8")
      .split("\n")
      .filter((l) => l && !l.startsWith("#") && l.includes("="))
      .map((l) => [l.slice(0, l.indexOf("=")).trim(), l.slice(l.indexOf("=") + 1).trim()]),
  );
  const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL ?? env.SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY, {
    auth: { persistSession: false },
  });
  const rates = await getExchangeRates();

  const prices: DerivedPrice[] = [];
  const pageSize = 2000;
  let from = 0;
  while (true) {
    const { data, error } = await sb
      .from("listings")
      .select("source,status,year,make,model,hammer_price,final_price,current_bid,original_currency")
      .eq("make", "Porsche")
      .range(from, from + pageSize - 1);
    if (error) throw error;
    if (!data || data.length === 0) break;
    for (const row of data) prices.push(derivePrice(row as any, { rates }));
    if (data.length < pageSize) break;
    from += pageSize;
  }

  const table = computeFactorTable(prices);
  const body = `// AUTO-GENERATED by scripts/generate-family-factors.ts — do not edit by hand.
import type { FamilyFactorTable } from "./types";

export const FAMILY_FACTOR_TABLE: FamilyFactorTable = ${JSON.stringify(table, null, 2)};
`;
  writeFileSync("src/lib/pricing/familyFactor.generated.ts", body);
  console.log("Wrote factor table:", table.porscheWide, "families:", Object.keys(table.byFamily));
}

// Allow both `node` CJS check and ESM. Support tsx execution.
const invokedDirectly =
  typeof require !== "undefined" && typeof module !== "undefined" && require.main === module;
if (invokedDirectly || process.argv[1]?.endsWith("generate-family-factors.ts")) {
  main().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
